name: 🐞 Bug Report
description: Report a bug you found
title: "[Bug Title here] "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea #description
    attributes:
      label: What happened?
      description: Also tell us about the expected behaviour. 
      placeholder: Tell us what you see and what you expected to see!
    validations:
      required: true

  - type: textarea #reproduce
    attributes:
      label: How can we reproduce this bug?
      description: Are there any specific steps you had to take in order to trigger the bug? Also elaborate on the expected behaviour and why you think it is expected. 
      placeholder: Kindly elaborate.
    validations:
      required: true

  - type: textarea #desktop info
    attributes:
      label: Desktop Information (Optional)
      description: Please provide the desktop configuration (OS,Browser, dependency version etc)
      placeholder: Type here.

  - type: dropdown #urgent
    attributes:
      label: Urgency (Optional)
      description: How urgent do you think it is to fix this bug?
      options:
        - Low priority
        - Medium priority
        - High priority
